title: Đoàn Ngọc Thành
email: dnt.doanngocthanh@gmail.com
description: >
  Hello world! Đây là blog cá nhân của tôi.
# If you publish to GitHub Pages as a project site (https://<user>.github.io/<repo>/)
# set `url` to the site root and `baseurl` to the repository name.
# For example: url: "https://doanngocthanh9x.github.io" and baseurl: "/doanngocthanh9x"
baseurl: "/doanngocthanh9x"
url: "https://doanngocthanh9x.github.io"
# baseurl: "" # nếu dùng GitHub Pages dưới user.github.io thì để trống
# url: "http://localhost:4000"
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/

# Excerpt separator
excerpt_separator: "<!--more-->"

# Build settings
collections: {}
